name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install zensical==0.0.24 mkdocs-static-i18n==1.3.1 mkdocs-git-revision-date-localized-plugin==1.5.1 pymdown-extensions==10.20.1

      - run: zensical build

      - name: Clean target directory
        uses: appleboy/ssh-action@v1
        with:
          host: wenzhi-ding.com
          username: deployer
          key: ${{ secrets.DEPLOY_KEY }}
          port: 33715
          script: rm -rf /var/www/guide/*

      - name: Deploy to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: wenzhi-ding.com
          username: deployer
          key: ${{ secrets.DEPLOY_KEY }}
          port: 33715
          source: "site/*"
          target: "/var/www/guide"
          strip_components: 1
          overwrite: true
          rm: false
